---
# Ansible playbook for deploying Docker challenges
- name: Deploy Docker challenges
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
    # Get the current user reliably
    - name: Get current username
      command: whoami
      register: whoami_result
      changed_when: false
      become: no

    # Set variables based on the username
    - name: Set user variables
      set_fact:
        current_user: "{{ whoami_result.stdout }}"
        challenges_dir: "/home/{{ whoami_result.stdout }}/azure-docker-playground/docker-challenges"

    # Ensure the challenges directory exists
    - name: Create challenges directory
      file:
        path: "{{ challenges_dir }}"
        state: directory
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0755'

    # Copy all challenge files at once from the local repository
    - name: Copy all challenge files
      copy:
        src: "{{ playbook_dir }}/../challenges/"
        dest: "{{ challenges_dir }}/"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0755'
        directory_mode: '0755'
        
    # Create .env file with ACR credentials
    - name: Create .env file with ACR credentials
      copy:
        content: |
          # Environment variables for Docker Challenges
          ACR_NAME={{ acr_name | default('') }}
          ACR_LOGIN_SERVER={{ acr_login_server | default('') }}
          USERNAME={{ current_user }}
          
          # ACR admin credentials
          ACR_USERNAME={{ acr_name | default('') }}
          # Note: Password will need to be manually added if needed
          ACR_PASSWORD=""
        dest: "{{ challenges_dir }}/.env"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0600'

    # Create Desktop directory if it doesn't exist
    - name: Check if Desktop directory exists
      stat:
        path: "/home/{{ current_user }}/Desktop"
      register: desktop_dir

    - name: Create Desktop directory if it doesn't exist
      file:
        path: "/home/{{ current_user }}/Desktop"
        state: directory
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0755'
      when: not desktop_dir.stat.exists

    # Create desktop shortcut for challenges
    - name: Create challenges desktop shortcut
      copy:
        content: |
          [Desktop Entry]
          Version=1.0
          Name=Docker Challenges
          Comment=Access Docker Security Challenges
          Exec=gnome-terminal --working-directory={{ challenges_dir }}
          Icon=utilities-terminal
          Terminal=false
          Type=Application
          Categories=Utility;Application;Development;
        dest: "/home/{{ current_user }}/Desktop/Challenges.desktop"
        owner: "{{ current_user }}"
        group: "{{ current_user }}"
        mode: '0755' # Make it executable
